// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"
)

const countAdminAccounts = `-- name: CountAdminAccounts :one
SELECT COUNT(*)
FROM accounts
WHERE is_admin = 1
`

func (q *Queries) CountAdminAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT
    account_id,
    username,
    username_key,
    password_hash,
    hash_algo,
    is_admin,
    created_at_unix_ms,
    updated_at_unix_ms
FROM accounts
WHERE account_id = ?
LIMIT 1
`

func (q *Queries) GetAccountByID(ctx context.Context, accountID string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, accountID)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.UsernameKey,
		&i.PasswordHash,
		&i.HashAlgo,
		&i.IsAdmin,
		&i.CreatedAtUnixMs,
		&i.UpdatedAtUnixMs,
	)
	return i, err
}

const getAccountByUsernameKey = `-- name: GetAccountByUsernameKey :one
SELECT
    account_id,
    username,
    username_key,
    password_hash,
    hash_algo,
    is_admin,
    created_at_unix_ms,
    updated_at_unix_ms
FROM accounts
WHERE username_key = ?
LIMIT 1
`

func (q *Queries) GetAccountByUsernameKey(ctx context.Context, usernameKey string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByUsernameKey, usernameKey)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.UsernameKey,
		&i.PasswordHash,
		&i.HashAlgo,
		&i.IsAdmin,
		&i.CreatedAtUnixMs,
		&i.UpdatedAtUnixMs,
	)
	return i, err
}

const getFirstAdminAccount = `-- name: GetFirstAdminAccount :one
SELECT
    account_id,
    username,
    username_key,
    password_hash,
    hash_algo,
    is_admin,
    created_at_unix_ms,
    updated_at_unix_ms
FROM accounts
WHERE is_admin = 1
ORDER BY created_at_unix_ms ASC, account_id ASC
LIMIT 1
`

func (q *Queries) GetFirstAdminAccount(ctx context.Context) (Account, error) {
	row := q.db.QueryRowContext(ctx, getFirstAdminAccount)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.UsernameKey,
		&i.PasswordHash,
		&i.HashAlgo,
		&i.IsAdmin,
		&i.CreatedAtUnixMs,
		&i.UpdatedAtUnixMs,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (
    account_id,
    username,
    username_key,
    password_hash,
    hash_algo,
    is_admin,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAccountParams struct {
	AccountID       string `json:"account_id"`
	Username        string `json:"username"`
	UsernameKey     string `json:"username_key"`
	PasswordHash    string `json:"password_hash"`
	HashAlgo        string `json:"hash_algo"`
	IsAdmin         int64  `json:"is_admin"`
	CreatedAtUnixMs int64  `json:"created_at_unix_ms"`
	UpdatedAtUnixMs int64  `json:"updated_at_unix_ms"`
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertAccount,
		arg.AccountID,
		arg.Username,
		arg.UsernameKey,
		arg.PasswordHash,
		arg.HashAlgo,
		arg.IsAdmin,
		arg.CreatedAtUnixMs,
		arg.UpdatedAtUnixMs,
	)
	return err
}
