// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Account struct {
	AccountID       string `json:"account_id"`
	Username        string `json:"username"`
	UsernameKey     string `json:"username_key"`
	PasswordHash    string `json:"password_hash"`
	HashAlgo        string `json:"hash_algo"`
	IsAdmin         int64  `json:"is_admin"`
	CreatedAtUnixMs int64  `json:"created_at_unix_ms"`
	UpdatedAtUnixMs int64  `json:"updated_at_unix_ms"`
}

type Task struct {
	TaskID            string `json:"task_id"`
	OwnerID           string `json:"owner_id"`
	RequestID         string `json:"request_id"`
	Capability        string `json:"capability"`
	InputJson         string `json:"input_json"`
	Status            string `json:"status"`
	CommandID         string `json:"command_id"`
	ResultJson        string `json:"result_json"`
	ErrorCode         string `json:"error_code"`
	ErrorMessage      string `json:"error_message"`
	CreatedAtUnixMs   int64  `json:"created_at_unix_ms"`
	UpdatedAtUnixMs   int64  `json:"updated_at_unix_ms"`
	DeadlineAtUnixMs  int64  `json:"deadline_at_unix_ms"`
	CompletedAtUnixMs int64  `json:"completed_at_unix_ms"`
	ExpiresAtUnixMs   int64  `json:"expires_at_unix_ms"`
}

type TrustedToken struct {
	TokenID         string `json:"token_id"`
	AccountID       string `json:"account_id"`
	Name            string `json:"name"`
	NameKey         string `json:"name_key"`
	TokenHash       string `json:"token_hash"`
	TokenMasked     string `json:"token_masked"`
	Generated       int64  `json:"generated"`
	CreatedAtUnixMs int64  `json:"created_at_unix_ms"`
	UpdatedAtUnixMs int64  `json:"updated_at_unix_ms"`
}

type WorkerCapability struct {
	NodeID         string `json:"node_id"`
	CapabilityName string `json:"capability_name"`
	MaxInflight    int64  `json:"max_inflight"`
}

type WorkerCredential struct {
	NodeID          string `json:"node_id"`
	SecretHash      string `json:"secret_hash"`
	HashAlgo        string `json:"hash_algo"`
	CreatedAtUnixMs int64  `json:"created_at_unix_ms"`
	UpdatedAtUnixMs int64  `json:"updated_at_unix_ms"`
}

type WorkerLabel struct {
	NodeID     string `json:"node_id"`
	LabelKey   string `json:"label_key"`
	LabelValue string `json:"label_value"`
}

type WorkerNode struct {
	NodeID             string `json:"node_id"`
	SessionID          string `json:"session_id"`
	Provisioned        int64  `json:"provisioned"`
	NodeName           string `json:"node_name"`
	ExecutorKind       string `json:"executor_kind"`
	Version            string `json:"version"`
	RegisteredAtUnixMs int64  `json:"registered_at_unix_ms"`
	LastSeenAtUnixMs   int64  `json:"last_seen_at_unix_ms"`
}
