// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package sqlc

import (
	"context"
)

const deleteTrustedTokenByIDAndAccount = `-- name: DeleteTrustedTokenByIDAndAccount :execrows
DELETE FROM trusted_tokens
WHERE token_id = ? AND account_id = ?
`

type DeleteTrustedTokenByIDAndAccountParams struct {
	TokenID   string `json:"token_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) DeleteTrustedTokenByIDAndAccount(ctx context.Context, arg DeleteTrustedTokenByIDAndAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTrustedTokenByIDAndAccount, arg.TokenID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTrustedTokenByAccountAndNameKey = `-- name: GetTrustedTokenByAccountAndNameKey :one
SELECT
    token_id,
    account_id,
    name,
    name_key,
    token_hash,
    token_masked,
    generated,
    created_at_unix_ms,
    updated_at_unix_ms
FROM trusted_tokens
WHERE account_id = ? AND name_key = ?
LIMIT 1
`

type GetTrustedTokenByAccountAndNameKeyParams struct {
	AccountID string `json:"account_id"`
	NameKey   string `json:"name_key"`
}

func (q *Queries) GetTrustedTokenByAccountAndNameKey(ctx context.Context, arg GetTrustedTokenByAccountAndNameKeyParams) (TrustedToken, error) {
	row := q.db.QueryRowContext(ctx, getTrustedTokenByAccountAndNameKey, arg.AccountID, arg.NameKey)
	var i TrustedToken
	err := row.Scan(
		&i.TokenID,
		&i.AccountID,
		&i.Name,
		&i.NameKey,
		&i.TokenHash,
		&i.TokenMasked,
		&i.Generated,
		&i.CreatedAtUnixMs,
		&i.UpdatedAtUnixMs,
	)
	return i, err
}

const getTrustedTokenByHash = `-- name: GetTrustedTokenByHash :one
SELECT
    token_id,
    account_id,
    name,
    name_key,
    token_hash,
    token_masked,
    generated,
    created_at_unix_ms,
    updated_at_unix_ms
FROM trusted_tokens
WHERE token_hash = ?
LIMIT 1
`

func (q *Queries) GetTrustedTokenByHash(ctx context.Context, tokenHash string) (TrustedToken, error) {
	row := q.db.QueryRowContext(ctx, getTrustedTokenByHash, tokenHash)
	var i TrustedToken
	err := row.Scan(
		&i.TokenID,
		&i.AccountID,
		&i.Name,
		&i.NameKey,
		&i.TokenHash,
		&i.TokenMasked,
		&i.Generated,
		&i.CreatedAtUnixMs,
		&i.UpdatedAtUnixMs,
	)
	return i, err
}

const getTrustedTokenByID = `-- name: GetTrustedTokenByID :one
SELECT
    token_id,
    account_id,
    name,
    name_key,
    token_hash,
    token_masked,
    generated,
    created_at_unix_ms,
    updated_at_unix_ms
FROM trusted_tokens
WHERE token_id = ?
LIMIT 1
`

func (q *Queries) GetTrustedTokenByID(ctx context.Context, tokenID string) (TrustedToken, error) {
	row := q.db.QueryRowContext(ctx, getTrustedTokenByID, tokenID)
	var i TrustedToken
	err := row.Scan(
		&i.TokenID,
		&i.AccountID,
		&i.Name,
		&i.NameKey,
		&i.TokenHash,
		&i.TokenMasked,
		&i.Generated,
		&i.CreatedAtUnixMs,
		&i.UpdatedAtUnixMs,
	)
	return i, err
}

const insertTrustedToken = `-- name: InsertTrustedToken :exec
INSERT INTO trusted_tokens (
    token_id,
    account_id,
    name,
    name_key,
    token_hash,
    token_masked,
    generated,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTrustedTokenParams struct {
	TokenID         string `json:"token_id"`
	AccountID       string `json:"account_id"`
	Name            string `json:"name"`
	NameKey         string `json:"name_key"`
	TokenHash       string `json:"token_hash"`
	TokenMasked     string `json:"token_masked"`
	Generated       int64  `json:"generated"`
	CreatedAtUnixMs int64  `json:"created_at_unix_ms"`
	UpdatedAtUnixMs int64  `json:"updated_at_unix_ms"`
}

func (q *Queries) InsertTrustedToken(ctx context.Context, arg InsertTrustedTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertTrustedToken,
		arg.TokenID,
		arg.AccountID,
		arg.Name,
		arg.NameKey,
		arg.TokenHash,
		arg.TokenMasked,
		arg.Generated,
		arg.CreatedAtUnixMs,
		arg.UpdatedAtUnixMs,
	)
	return err
}

const listTrustedTokensByAccount = `-- name: ListTrustedTokensByAccount :many
SELECT
    token_id,
    account_id,
    name,
    name_key,
    token_hash,
    token_masked,
    generated,
    created_at_unix_ms,
    updated_at_unix_ms
FROM trusted_tokens
WHERE account_id = ?
ORDER BY created_at_unix_ms ASC, token_id ASC
`

func (q *Queries) ListTrustedTokensByAccount(ctx context.Context, accountID string) ([]TrustedToken, error) {
	rows, err := q.db.QueryContext(ctx, listTrustedTokensByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrustedToken
	for rows.Next() {
		var i TrustedToken
		if err := rows.Scan(
			&i.TokenID,
			&i.AccountID,
			&i.Name,
			&i.NameKey,
			&i.TokenHash,
			&i.TokenMasked,
			&i.Generated,
			&i.CreatedAtUnixMs,
			&i.UpdatedAtUnixMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
